export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';
export const BUY_PRODUCT = 'BUY_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const INCREMENT_PRODUCT = 'INCREMENT_PRODUCT';
export const DECREMENT_PRODUCT = 'DECREMENT_PRODUCT';
export const HANDLE_COUNT_PRODUCT = 'HANDLE_COUNT_PRODUCT';



